# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1czCnlAVGyn35OQ0-Ps2pHsrJT_fb4vha
"""

import os
import warnings
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import pandas as pd
import streamlit as st

warnings.filterwarnings("ignore")

st.set_page_config(
    page_title="E-Commerce Dashboard",
    layout="wide",
    initial_sidebar_state="expanded"
)

st.markdown("""
<style>
    .stApp {
        background: linear-gradient(180deg, #F5F9FF 0%, #EEF4FF 100%);
    }

    .block-container {
        padding-top: 2rem;
        padding-bottom: 2rem;
        padding-left: 2.2rem;
        padding-right: 2.2rem;
        max-width: 1280px;
    }

    #MainMenu {visibility: hidden;}
    footer {visibility: hidden;}

    .custom-card {
        background: #FFFFFF;
        border: 1px solid #D6E4FF;
        border-radius: 18px;
        padding: 1.2rem 1.2rem 1rem 1.2rem;
        box-shadow: 0 6px 20px rgba(30, 64, 175, 0.08);
        margin-bottom: 1rem;
    }

    .hero-box {
        background: linear-gradient(135deg, #1D4ED8 0%, #3B82F6 100%);
        padding: 1.6rem 1.6rem 1.3rem 1.6rem;
        border-radius: 22px;
        color: white;
        box-shadow: 0 10px 28px rgba(29, 78, 216, 0.25);
        margin-bottom: 1.2rem;
    }

    .hero-title {
        font-size: 2rem;
        font-weight: 800;
        margin-bottom: 0.25rem;
        line-height: 1.2;
    }

    .hero-subtitle {
        font-size: 1rem;
        opacity: 0.95;
        margin-bottom: 0.55rem;
    }

    .hero-badge {
        display: inline-block;
        background: rgba(255,255,255,0.18);
        border: 1px solid rgba(255,255,255,0.25);
        border-radius: 999px;
        padding: 0.35rem 0.8rem;
        font-size: 0.86rem;
        margin-right: 0.45rem;
        margin-top: 0.35rem;
    }

    .metric-box {
        background: #FFFFFF;
        border: 1px solid #D6E4FF;
        border-radius: 18px;
        padding: 1rem 1rem 0.9rem 1rem;
        box-shadow: 0 4px 16px rgba(30, 64, 175, 0.06);
    }

    .metric-label {
        color: #4B5563;
        font-size: 0.92rem;
        margin-bottom: 0.2rem;
    }

    .metric-value {
        color: #1D4ED8;
        font-size: 2rem;
        font-weight: 800;
        line-height: 1.1;
    }

    .metric-note {
        color: #6B7280;
        font-size: 0.8rem;
        margin-top: 0.35rem;
    }

    .section-note {
        color: #4B5563;
        font-size: 0.95rem;
        margin-top: -0.15rem;
        margin-bottom: 0.9rem;
    }

    section[data-testid="stSidebar"] {
        background: linear-gradient(180deg, #F5F9FF 0%, #EAF1FF 100%);
        border-right: 1px solid #D6E4FF;
    }

    section[data-testid="stSidebar"] .block-container {
        padding-top: 1.5rem;
    }

    button[data-baseweb="tab"] {
        border-radius: 12px;
        padding: 0.55rem 1rem;
        background: #EAF1FF;
        border: 1px solid #D6E4FF;
        margin-right: 0.35rem;
    }

    button[data-baseweb="tab"][aria-selected="true"] {
        background: #1D4ED8 !important;
        color: white !important;
        border: 1px solid #1D4ED8 !important;
    }

    .table-card {
        background: #FFFFFF;
        border: 1px solid #D6E4FF;
        border-radius: 16px;
        padding: 0.8rem;
        box-shadow: 0 4px 14px rgba(30, 64, 175, 0.06);
        margin-bottom: 1rem;
    }

    .soft-divider {
        height: 1px;
        background: linear-gradient(to right, rgba(0,0,0,0), #D6E4FF, rgba(0,0,0,0));
        margin-top: 0.8rem;
        margin-bottom: 1.2rem;
    }
</style>
""", unsafe_allow_html=True)

COLOR_PRIMARY = "#2563EB"
COLOR_GOLD = "#F59E0B"
COLOR_MUTED = "#93C5FD"
COLOR_BG = "#F8FAFC"


@st.cache_data
def load_data():
    base_dir = os.path.dirname(__file__)
    csv_path = os.path.join(base_dir, "main_data.csv")
    df = pd.read_csv(csv_path)

    df["order_purchase_timestamp"] = pd.to_datetime(df["order_purchase_timestamp"])
    df["revenue"] = df["price"] + df["freight_value"]

    return df


all_df = load_data()

# Filter default sesuai revisi notebook: periode 2017–2018
default_min_date = max(all_df["order_purchase_timestamp"].min().date(), pd.to_datetime("2016").date())
default_max_date = min(all_df["order_purchase_timestamp"].max().date(), pd.to_datetime("2018").date())

with st.sidebar:
    st.markdown("## E-Commerce")
    st.caption("Filter dashboard interaktif")
    st.markdown("---")

    date_range = st.date_input(
        "Filter Rentang Tanggal",
        value=[default_min_date, default_max_date],
        min_value=all_df["order_purchase_timestamp"].min().date(),
        max_value=all_df["order_purchase_timestamp"].max().date()
    )

    st.markdown("---")

if len(date_range) == 2:
    start_date, end_date = date_range
    filtered_df = all_df[
        (all_df["order_purchase_timestamp"].dt.date >= start_date) &
        (all_df["order_purchase_timestamp"].dt.date <= end_date)
    ].copy()
else:
    filtered_df = all_df[
        (all_df["order_purchase_timestamp"].dt.date >= default_min_date) &
        (all_df["order_purchase_timestamp"].dt.date <= default_max_date)
    ].copy()

filtered_df["order_year_month"] = filtered_df["order_purchase_timestamp"].dt.to_period("M").astype(str)

with st.sidebar:
    st.info(f"**Total pesanan:** {filtered_df['order_id'].nunique():,}")
    st.info(f"**Total pelanggan:** {filtered_df['customer_unique_id'].nunique():,}")
    st.info(f"**Total revenue:** R$ {filtered_df['revenue'].sum():,.0f}")

st.markdown("""
<div class="hero-box">
    <div class="hero-title">Dashboard Analisis E-Commerce</div>
    <div class="hero-subtitle">
        Ringkasan performa transaksi, pelanggan, kategori produk, wilayah pada periode 2016–2018.
    </div>
    <span class="hero-badge">Dataset E-Commerce</span>
    <span class="hero-badge">Periode 2016–2018</span>
    <span class="hero-badge">Interactive Dashboard</span>
</div>
""", unsafe_allow_html=True)

col1, col2, col3 = st.columns(3)

with col1:
    st.markdown(f"""
    <div class="metric-box">
        <div class="metric-label">Total Pesanan</div>
        <div class="metric-value">{filtered_df['order_id'].nunique():,}</div>
        <div class="metric-note">Jumlah order unik dalam periode terpilih</div>
    </div>
    """, unsafe_allow_html=True)

with col2:
    st.markdown(f"""
    <div class="metric-box">
        <div class="metric-label">Total Pelanggan</div>
        <div class="metric-value">{filtered_df['customer_unique_id'].nunique():,}</div>
        <div class="metric-note">Pelanggan unik yang melakukan transaksi</div>
    </div>
    """, unsafe_allow_html=True)

with col3:
    total_revenue = filtered_df["revenue"].sum()
    revenue_display = f"R$ {total_revenue/1e6:.2f}M" if total_revenue >= 1e6 else f"R$ {total_revenue:,.0f}"
    st.markdown(f"""
    <div class="metric-box">
        <div class="metric-label">Total Revenue</div>
        <div class="metric-value">{revenue_display}</div>
        <div class="metric-note">Akumulasi price + freight value</div>
    </div>
    """, unsafe_allow_html=True)

st.markdown('<div class="soft-divider"></div>', unsafe_allow_html=True)

tab1, tab2, tab3 = st.tabs([
    "Tren Bulanan",
    "Kategori Produk",
    "Distribusi Wilayah"
])

with tab1:
    st.markdown('<div class="custom-card">', unsafe_allow_html=True)
    st.subheader("Bagaimana tren penjualan bulanan selama periode 2016–2018?")
    st.markdown(
        '<div class="section-note">Pesanan ditampilkan secara bulanan untuk melihat pola pertumbuhan dan periode puncak transaksi pada periode analisis.</div>',
        unsafe_allow_html=True
    )

    monthly = filtered_df.groupby("order_year_month").agg(
    total_revenue=("revenue", "sum")
).reset_index()

    fig, ax = plt.subplots(figsize=(14, 6))
    fig.patch.set_facecolor(COLOR_BG)

    x = range(len(monthly))

    ax.plot(x, monthly["total_revenue"], color=COLOR_PRIMARY, linewidth=2, marker="o")

    ax.set_xticks(list(x))
    ax.set_xticklabels(monthly["order_year_month"], rotation=45, ha="right", fontsize=8)

    ax.set_title("Tren Revenue Bulanan (2016–2018)")
    ax.set_ylabel("Revenue")

    ax.yaxis.set_major_formatter(
        mticker.FuncFormatter(lambda y, _: f"{int(y):,}")
    )

    ax.grid(axis="y", linestyle="--", alpha=0.5)

    st.pyplot(fig, use_container_width=True)
    plt.close(fig)
    st.markdown('</div>', unsafe_allow_html=True)

with tab2:
    st.markdown('<div class="custom-card">', unsafe_allow_html=True)
    st.subheader("Kategori produk apa yang memiliki jumlah penjualan selama periode 2016–2018?")
    st.markdown(
        '<div class="section-note">Perbandingan kategori terlaris berdasarkan jumlah pesanan tertinggi pada periode analisis.</div>',
        unsafe_allow_html=True
    )
    top_n = st.slider("Top N Kategori", min_value=5, max_value=20, value=10)
    cat_agg = filtered_df.groupby("product_category_name_english").agg(
    total_revenue=("revenue", "sum")
).reset_index()

    top_revenue = cat_agg.sort_values("total_revenue", ascending=False).head(top_n)

    fig, ax = plt.subplots(figsize=(14, 7))
    fig.patch.set_facecolor(COLOR_BG)

    ax.barh(
        top_revenue["product_category_name_english"][::-1],
        top_revenue["total_revenue"][::-1],
        color=COLOR_PRIMARY
    )

    ax.set_title("Top Kategori berdasarkan Revenue (2016–2018)")
    ax.set_xlabel("Revenue")

    ax.xaxis.set_major_formatter(
        mticker.FuncFormatter(lambda x, _: f"{int(x):,}")
    )

    ax.grid(axis="x", linestyle="--", alpha=0.5)

    st.pyplot(fig, use_container_width=True)
    plt.close(fig)

    st.markdown('</div>', unsafe_allow_html=True)

with tab3:
    st.markdown('<div class="custom-card">', unsafe_allow_html=True)
    st.subheader("Bagaimana distribusi pelanggan berdasarkan wilayah selama periode 2016–2018?")
    st.markdown(
        '<div class="section-note">Distribusi pelanggan ditinjau dari state dan kota untuk mengetahui pusat konsentrasi pasar pada periode analisis.</div>',
        unsafe_allow_html=True
    )

    bystate = filtered_df.groupby("customer_state")["customer_unique_id"].nunique().sort_values(ascending=False).reset_index()
    bystate.columns = ["customer_state", "customer_count"]

    top10_state = bystate.head(10)

    fig, ax = plt.subplots(figsize=(14, 7))
    fig.patch.set_facecolor(COLOR_BG)

    ax.barh(
        top10_state["customer_state"][::-1],
        top10_state["customer_count"][::-1],
        color=COLOR_PRIMARY
        )

    ax.set_title("Top 10 State Customer (2016–2018)")
    ax.set_xlabel("Jumlah Customer")

    ax.grid(axis="x", linestyle="--", alpha=0.5)

    st.pyplot(fig, use_container_width=True)
    plt.close(fig)

    st.markdown('</div>', unsafe_allow_html=True)

st.markdown('<div class="soft-divider"></div>', unsafe_allow_html=True)
st.caption("Dashboard Proyek Fundamental Analisis Data | CDCC206D6Y1022 | Dataset: E-Commerce")